# Important version de docker-compose à utiliser
version: "3"

services:
# nom du service
    influxdb:
# nom du container
        container_name: influxdb
# image officielle d'influxDB
        image: influxdb:1.7.10-alpine
# synchronise des élements entre l'hôte et le container avec cette syntaxe dossier_sur_hôte:dossier_dans_container
        volumes:
            - ./influxdb/:/etc/influxdb/
            - influxdb-lib:/var/lib/influxdb
# ouverture des ports du container
        ports:
            - 8086:8086
# Toujours redémarrer le conteneur s'il s'arrête. S'il est arrêté manuellement, il n'est activé que lorsque le daemon Docker
# redémarre, comme de base ce daemon s'active lors du boot,
# alors avec cette commande nos containers démarrent aussi lors du boot sans intervention humaine.
        restart: always

    mosquitto:
        container_name: mosquitto
        image: lpiotia/mosquitto:latest
        volumes:
            - ./data/mosquitto.conf:/etc/mosquitto/mosquitto.conf
            - ./data/pwfile:/etc/mosquitto/pwfile
            - ./data:/var/lib/mosquitto
        ports:
            - 1883:1883
            - 8883:8883
            - 8080:8080
        restart: always

# avec la commande suivante on indique que c'est docker-compose qui
# doit créer ce volume et le gérer, nous n'intervenons pas dessus
# car il doit contenir une sauvegarde de la base de données sur l'hôte
volumes:
  influxdb-lib:
    external: false